name = "gifts"
type = "javascript"
account_id = "7bb716ee4887455cd0265e5b6f29e575"
workers_dev = true
compatibility_date = "2021-11-22"

[site]
bucket = "./public"
entry-point = "workers-site"

[build]
command = "npm install && npm run build && cd workers-site && npm install && npm run build"

[build.upload]
format = "service-worker"
